services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
